### ISSUE TITLE
Dapr instances started by Sidekick doesn't show in Dashboard

### ISSUE THREAD

**Issue by fbridger** [man-group/dapr-sidekick-dotnet#20]
## Expected Behavior

Dapr instances launched by Sidekick show show in Dapr Dashboard

## Actual Behavior

Dapr Dashboard is not showing any application in the Dapr Applications table

## Steps to Reproduce the Problem

1. Launch a ASP.Net Core Web API with Sidekick enabled.
2. Start Dapr Dashboard
    ```
    dapr dashboard
    ```
3. Open Dapr Dashboard in browser http://localhost:8080
4. Check that Dapr application is not listed

**Comment by a-elsheikh** [comment]
Hey @fbridger thanks for checking out sidekick :smile: - the reason this doesn't currently work is because when running in standalone mode the dashboard identifies active/running dapr apps by ultimately scanning for instances of the dapr cli process (dapr.exe) - as sidekick circumvents the use of the cli all together by only using the runtime executable (daprd.exe) then it is missed by this process scan. 

dashboard getStandaloneInstances() - https://github.com/dapr/dashboard/blob/master/pkg/instances/instances.go#L435
standalone.List() - https://github.com/dapr/cli/blob/master/pkg/standalone/list.go#L52

For this to work a change would need to be made to the code base to allow identification of dapr instances via runtime alone (daprd.exe) removing the cli as a dependency..

**Comment by fbridger** [comment]
Got it. Thanks for the detailed explanation.

I've started using Sidekick to be able to improve the development experience in Visual Studio when using Dapr. Incredible work done here! Thanks for allowing us to make use of it!

**Comment by aktxyz** [comment]
Wow, this explains why my stuff was no showing up in the dashboard also (pre sidekick).  I had a script that kicked off things and it used daprd directly !

Do you know if any issue has been opened on the dapr side for this? seems like the dashboard scan should be based on something required, not a helper that runs the required stuff.

**Comment by a-elsheikh** [comment]
> Wow, this explains why my stuff was no showing up in the dashboard also (pre sidekick). I had a script that kicked off things and it used daprd directly !
> 
> Do you know if any issue has been opened on the dapr side for this? seems like the dashboard scan should be based on something required, not a helper that runs the required stuff.

Not that I know of, though I can see you've raised an issue in the dapr/dashboard repo 👍

**Comment by aktxyz** [comment]
fingers crossed !

**Comment by aktxyz** [comment]
here is the issue opened on the dashboard fyi ...

https://github.com/dapr/dashboard/issues/163
