### ISSUE TITLE
Invoking Actor methods from .Net Framework

### ISSUE THREAD

**Issue by msislam3** [man-group/dapr-sidekick-dotnet#43]
I am using the WCF Sample project as base to enable DAPR in a .NET Framework app. I was wondering if it's possible to invoke Actor methods running in other DAPR services from a .NET Framework service. I see example of calling Service methods using HTTP Client created using HttpClientFactory but I am not sure how to call an Actor method. I can't use the official Dapr.Actor package as it relies on .NET Core

**Comment by badgeratu** [comment]
The Dapr Virtual Actor feature is heavily dependent on the official Dapr SDK, which is why only a few SDK's currently implement it. The Dapr Sidekick library is a slim component with no dependencies on the Dapr SDK whose job is purely to launch, configure and monitor the Dapr sidecar as a dependent process. If you want to invoke Virtual Actors from the .NET Framework I suggest raising an Issue against the official Dapr SDK.

**Comment by msislam3** [comment]
That's fair. I'll raise an issue in the official SDK repo
